= README

== Local development

* Start the navigation application with the following parameters:

[source, bash]
----
ng serve --publicHost="http://localhost:4200"
----
* Start the application with the following default jvm args:
** "wicket.deployment" with the value "development", e.g. -Dwicket.deployment=development
** "navapp.location" with the location of the cdn, e.g. -Dnavapp.location="http://localhost:4200"

== Update the navapp and navapp-communication libary

The navigation application ( https://www.npmjs.com/package/@bloomreach/navapp[navapp] )
and the navigation applicaiton communication library ( https://www.npmjs.com/package/@bloomreach/navapp-communication[navapp-communication] ) are projects
that are hosted on https://www.npmjs.com[npm].

The navigation application will load from a cdn in a production environment that will always serve the latest version.

As a backup a version from the navigation application is added to the build as well. During the maven build
of this module it is included in the artifact of this module.

When a new version is available maven will not pull in the latest version automatically. The
steps needed to update to the latest version are described below.


==== Prepare

Make sure the directory of engine module is clean ( Stage and commit your changes or revert them )

==== Current versions

Check what is the current version of the navapp and navapp-communication in the dependencies section of the
package.json file.

.package.json
[source, json]
----
include::./package.json[]
----

==== New Versions
[source, bash]
----
npm view @bloomreach/navapp <1>
npm view @bloomreach/navapp-communication <2>
----

<1> Get information about the last and next version of the navapp.
<2> Get information about the last and next version of the navapp-communication library

==== Update
[source, bash]
----
npm install  @bloomreach/navapp@next <1>
npm install @bloomreach/navapp-communication@next <2>
----
<1> Install next version if needed for navapp
<2> Install next version if needed for navapp-communication library

Inspect the package.json and package-lock.json file. They now use the latest version of the navapp.
