definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        hst:allowedorigins: [http://localhost:3000]
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:xmspaexample/hst:sites/xmspaexample
          hst:pagemodelapi: resourceapi
          hst:responseheaders: ['Access-Control-Allow-Origin: *']
