(function(){function j(c,f,j,k){var a,h,i,l,p,n,f=f||{};h=f.indent_size||4;i=f.indent_char||" ";p=f.brace_style||"collapse";l=0===f.max_char?Infinity:f.max_char||250;n=f.unformatted||"a span bdo em strong dfn code samp kbd var cite abbr acronym q sub sup tt i b big small u s strike font ins del pre address dt h1 h2 h3 h4 h5 h6".split(" ");a=new function(){this.pos=0;this.token="";this.current_mode="CONTENT";this.tags={parent:"parent1",parentcount:1,parent1:""};this.token_text=this.last_token=this.last_text=
this.token_type=this.tag_type="";this.Utils={whitespace:["\n","\r","\t"," "],single_token:"br input link meta !doctype basefont base area hr wbr param img isindex ?xml embed ?php ? ?=".split(" "),extra_liners:["head","body","/html"],in_array:function(d,b){for(var a=0;a<b.length;a++)if(d===b[a])return!0;return!1}};this.get_content=function(){for(var d="",b=[],a=!1;"<"!==this.input.charAt(this.pos);){if(this.pos>=this.input.length)return b.length?b.join(""):["","TK_EOF"];d=this.input.charAt(this.pos);
this.pos++;this.line_char_count++;if(this.Utils.in_array(d,this.Utils.whitespace))b.length&&(a=!0),this.line_char_count--;else{if(a){if(this.line_char_count>=this.max_char){b.push("\n");for(a=0;a<this.indent_level;a++)b.push(this.indent_string);this.line_char_count=0}else b.push(" "),this.line_char_count++;a=!1}b.push(d)}}return b.length?b.join(""):""};this.get_contents_to=function(d){if(this.pos===this.input.length)return["","TK_EOF"];var a="",d=RegExp("</"+d+"\\s*>","igm");d.lastIndex=this.pos;
d=(d=d.exec(this.input))?d.index:this.input.length;this.pos<d&&(a=this.input.substring(this.pos,d),this.pos=d);return a};this.record_tag=function(d){this.tags[d+"count"]?this.tags[d+"count"]++:this.tags[d+"count"]=1;this.tags[d+this.tags[d+"count"]]=this.indent_level;this.tags[d+this.tags[d+"count"]+"parent"]=this.tags.parent;this.tags.parent=d+this.tags[d+"count"]};this.retrieve_tag=function(d){if(this.tags[d+"count"]){for(var a=this.tags.parent;a&&d+this.tags[d+"count"]!==a;)a=this.tags[a+"parent"];
a&&(this.indent_level=this.tags[d+this.tags[d+"count"]],this.tags.parent=this.tags[a+"parent"]);delete this.tags[d+this.tags[d+"count"]+"parent"];delete this.tags[d+this.tags[d+"count"]];1===this.tags[d+"count"]?delete this.tags[d+"count"]:this.tags[d+"count"]--}};this.get_tag=function(a){var b="",g=[],b="",e=!1,c,f=this.pos,h=this.line_char_count,a=void 0!==a?a:!1;do{if(this.pos>=this.input.length)return a&&(this.pos=f,this.line_char_count=h),g.length?g.join(""):["","TK_EOF"];b=this.input.charAt(this.pos);
this.pos++;this.line_char_count++;if(this.Utils.in_array(b,this.Utils.whitespace))e=!0,this.line_char_count--;else{if("'"===b||'"'===b)if(!g[1]||"!"!==g[1])b+=this.get_unformatted(b),e=!0;"="===b&&(e=!1);g.length&&("="!==g[g.length-1]&&">"!==b&&e)&&(this.line_char_count>=this.max_char?(this.print_newline(!1,g),this.line_char_count=0):(g.push(" "),this.line_char_count++),e=!1);"<"===b&&(c=this.pos-1);g.push(b)}}while(">"!==b);b=g.join("");e=-1!==b.indexOf(" ")?b.indexOf(" "):b.indexOf(">");e=b.substring(1,
e).toLowerCase();if("/"===b.charAt(b.length-2)||this.Utils.in_array(e,this.Utils.single_token))a||(this.tag_type="SINGLE");else if("script"===e)a||(this.record_tag(e),this.tag_type="SCRIPT");else if("style"===e)a||(this.record_tag(e),this.tag_type="STYLE");else if(this.is_unformatted(e,n))b=this.get_unformatted("</"+e+">",b),g.push(b),0<c&&this.Utils.in_array(this.input.charAt(c-1),this.Utils.whitespace)&&g.splice(0,0,this.input.charAt(c-1)),c=this.pos-1,this.Utils.in_array(this.input.charAt(c+1),
this.Utils.whitespace)&&g.push(this.input.charAt(c+1)),this.tag_type="SINGLE";else if("!"===e.charAt(0))if(-1!==e.indexOf("[if")){if(-1!==b.indexOf("!IE")&&(b=this.get_unformatted("--\>",b),g.push(b)),!a)this.tag_type="START"}else-1!==e.indexOf("[endif")?(this.tag_type="END",this.unindent()):-1!==e.indexOf("[cdata[")?(b=this.get_unformatted("]]\>",b),g.push(b),a||(this.tag_type="SINGLE")):(b=this.get_unformatted("--\>",b),g.push(b),this.tag_type="SINGLE");else a||("/"===e.charAt(0)?(this.retrieve_tag(e.substring(1)),
this.tag_type="END"):(this.record_tag(e),this.tag_type="START"),this.Utils.in_array(e,this.Utils.extra_liners)&&this.print_newline(!0,this.output));a&&(this.pos=f,this.line_char_count=h);return g.join("")};this.get_unformatted=function(a,b){if(b&&-1!==b.toLowerCase().indexOf(a))return"";var c="",e="",f=!0;do{if(this.pos>=this.input.length)break;c=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(c,this.Utils.whitespace)){if(!f){this.line_char_count--;continue}if("\n"===c||"\r"===c){e+=
"\n";this.line_char_count=0;continue}}e+=c;this.line_char_count++;f=!0}while(-1===e.toLowerCase().indexOf(a));return e};this.get_token=function(){var a;if("TK_TAG_SCRIPT"===this.last_token||"TK_TAG_STYLE"===this.last_token){var b=this.last_token.substr(7);a=this.get_contents_to(b);return"string"!==typeof a?a:[a,"TK_"+b]}if("CONTENT"===this.current_mode)return a=this.get_content(),"string"!==typeof a?a:[a,"TK_CONTENT"];if("TAG"===this.current_mode)return a=this.get_tag(),"string"!==typeof a?a:[a,"TK_TAG_"+
this.tag_type]};this.get_full_indent=function(a){a=this.indent_level+a||0;return 1>a?"":Array(a+1).join(this.indent_string)};this.is_unformatted=function(a,b){if(!this.Utils.in_array(a,b))return!1;if("a"!==a.toLowerCase()||!this.Utils.in_array("a",b))return!0;var c=(this.get_tag(!0)||"").match(/^\s*<\s*\/?([a-z]*)\s*[^>]*>\s*$/);return!c||this.Utils.in_array(c,b)?!0:!1};this.printer=function(a,b,c,e,f){this.input=a||"";this.output=[];this.indent_character=b;this.indent_string="";this.indent_size=
c;this.brace_style=f;this.indent_level=0;this.max_char=e;for(a=this.line_char_count=0;a<this.indent_size;a++)this.indent_string+=this.indent_character;this.print_newline=function(a,b){this.line_char_count=0;if(b&&b.length){if(!a)for(;this.Utils.in_array(b[b.length-1],this.Utils.whitespace);)b.pop();b.push("\n");for(var c=0;c<this.indent_level;c++)b.push(this.indent_string)}};this.print_token=function(a){this.output.push(a)};this.indent=function(){this.indent_level++};this.unindent=function(){0<this.indent_level&&
this.indent_level--}};return this};for(a.printer(c,i,h,l,p);;){c=a.get_token();a.token_text=c[0];a.token_type=c[1];if("TK_EOF"===a.token_type)break;switch(a.token_type){case "TK_TAG_START":a.print_newline(!1,a.output);a.print_token(a.token_text);a.indent();a.current_mode="CONTENT";break;case "TK_TAG_STYLE":case "TK_TAG_SCRIPT":a.print_newline(!1,a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_END":"TK_CONTENT"===a.last_token&&""===a.last_text&&(c=a.token_text.match(/\w+/)[0],
h=a.output[a.output.length-1].match(/<\s*(\w+)/),(null===h||h[1]!==c)&&a.print_newline(!0,a.output));a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_SINGLE":c=a.token_text.match(/^\s*<([a-z]+)/i);(!c||!a.Utils.in_array(c[1],n))&&a.print_newline(!1,a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_CONTENT":""!==a.token_text&&a.print_token(a.token_text);a.current_mode="TAG";break;case "TK_STYLE":case "TK_SCRIPT":if(""!==a.token_text){a.output.push("\n");
var c=a.token_text,m;i=1;"TK_SCRIPT"===a.token_type?m="function"===typeof j&&j:"TK_STYLE"===a.token_type&&(m="function"===typeof k&&k);"keep"===f.indent_scripts?i=0:"separate"===f.indent_scripts&&(i=-a.indent_level);h=a.get_full_indent(i);m?c=m(c.replace(/^\s*/,h),f):(l=c.match(/^\s*/)[0].match(/[^\n\r]*$/)[0].split(a.indent_string).length-1,i=a.get_full_indent(i-l),c=c.replace(/^\s*/,h).replace(/\r\n|\r|\n/g,"\n"+i).replace(/\s*$/,""));c&&(a.print_token(c),a.print_newline(!0,a.output))}a.current_mode=
"TAG"}a.last_token=a.token_type;a.last_text=a.token_text}return a.output.join("")}if("function"===typeof define)define(function(c,f){var o=c("./beautify.js").js_beautify,k=c("./beautify-css.js").css_beautify;f.html_beautify=function(a,c){return j(a,c,o,k)}});else if("undefined"!==typeof exports){var o=require("./beautify.js").js_beautify,q=require("./beautify-css.js").css_beautify;exports.html_beautify=function(c,f){return j(c,f,o,q)}}else"undefined"!==typeof window?window.html_beautify=function(c,
f){return j(c,f,window.js_beautify,window.css_beautify)}:"undefined"!==typeof global&&(global.html_beautify=function(c,f){return j(c,f,global.js_beautify,global.css_beautify)})})();