(function(){function u(q,g){return(new la(q,g)).beautify()}function la(q,g){var u,M,v,U,Y,N,V,Z,n,$,O,aa,P,w,r,H,Q,I;function fa(a,c){return{mode:c,last_text:a?a.last_text:"",last_word:a?a.last_word:"",var_line:!1,var_line_tainted:!1,var_line_reindented:!1,in_html_comment:!1,multiline_array:!1,if_block:!1,do_block:!1,do_while:!1,in_case_statement:!1,in_case:!1,case_body:!1,indentation_level:a?a.indentation_level+(a.var_line&&a.var_line_reindented?1:0):0,ternary_depth:0}}function ga(a){for(a=void 0===
a?!1:a;j.length&&(" "===j[j.length-1]||j[j.length-1]===x||j[j.length-1]===J||a&&("\n"===j[j.length-1]||"\r"===j[j.length-1]));)j.pop()}function ba(a){return a.replace(/^\s\s*|\s\s*$/,"")}function y(){return j.length&&"\n"===j[j.length-1]}function R(a){a=void 0===a?!1:a;if(u&&!a){var c="",c=0;a:{c=j.length-1;0>c&&(c+=j.length);c>j.length-1&&(c=j.length-1);for(c++;0<c--;)if(c in j&&"\n"===j[c])break a;c=-1}c+=1;c<j.length&&(c=j.slice(c).join(""),c=c.length+e.length+(d?1:0),c>=u&&(a=!0))}if((M&&z||a)&&
!y())f(!1,!0),K=!0,z=!1}function f(b,c){d=K=!1;if(!c&&";"!==a.last_text)for(;a.mode===w&&!a.if_block;)B();a.mode===r&&(a.multiline_array=!0);j.length&&(b||!y())&&j.push("\n")}function ca(b){void 0===b?b=1:"number"!==typeof b&&(b=b?1:0);if(""!==a.last_text)for(var c=0;c<b;c+=1)j.push(x)}function k(b){b=b||e;y()&&(v&&a.mode===r&&C.length?j.push(C.join("")+""):(J&&j.push(J),ca(a.indentation_level),ca(a.var_line&&a.var_line_reindented),ca(K)));K=!1;if(d&&j.length){var c=j[j.length-1];!y()&&(" "!==c&&
c!==x)&&j.push(" ")}d=!1;j.push(b)}function A(b){a?(W.push(a),t=a):t=fa(null,b);a=fa(t,b)}function S(a){return m(a,[H,Q,I])}function B(){0<W.length&&(t=a,a=W.pop())}function da(){return"do"===a.last_text||"else"===a.last_text&&"if"!==e||"TK_END_EXPR"===h&&(t.mode===Q||t.mode===I)?(R(),A(w),a.indentation_level+=1,K=!1,!0):!1}function L(a){return m(a,"case return do if throw else".split(" "))}function m(a,c){for(var b=0;b<c.length;b+=1)if(c[b]===a)return!0;return!1}function ha(a){for(var c=b,h=i.charAt(c);m(h,
ea)&&h!==a;){c++;if(c>=o)return!1;h=i.charAt(c)}return h===a}function ia(){var l;s=0;if(b>=o)return["","TK_EOF"];z=!1;C=[];var c=i.charAt(b);for(b+=1;m(c,ea);){"\n"===c?(s+=1,C=[]):s&&(c===x?C.push(x):"\r"!==c&&C.push(" "));if(b>=o)return["","TK_EOF"];c=i.charAt(b);b+=1}if(m(c,X)){if(b<o)for(;m(i.charAt(b),X)&&!(c+=i.charAt(b),b+=1,b===o););if(b!==o&&c.match(/^[0-9]+[Ee]$/)&&("-"===i.charAt(b)||"+"===i.charAt(b))){var d=i.charAt(b);b+=1;var f=ia(),c=c+(d+f[0]);return[c,"TK_WORD"]}return"in"===c?[c,
"TK_OPERATOR"]:[c,"TK_WORD"]}if("("===c||"["===c)return[c,"TK_START_EXPR"];if(")"===c||"]"===c)return[c,"TK_END_EXPR"];if("{"===c)return[c,"TK_START_BLOCK"];if("}"===c)return[c,"TK_END_BLOCK"];if(";"===c)return[c,"TK_SEMICOLON"];if("/"===c){d="";f=!0;if("*"===i.charAt(b)){b+=1;if(b<o)for(;b<o&&!("*"===i.charAt(b)&&i.charAt(b+1)&&"/"===i.charAt(b+1));){c=i.charAt(b);d+=c;if("\n"===c||"\r"===c)f=!1;b+=1;if(b>=o)break}b+=2;return f&&0===s?["/*"+d+"*/","TK_INLINE_COMMENT"]:["/*"+d+"*/","TK_BLOCK_COMMENT"]}if("/"===
i.charAt(b)){for(d=c;"\r"!==i.charAt(b)&&"\n"!==i.charAt(b)&&!(d+=i.charAt(b),b+=1,b>=o););return[d,"TK_COMMENT"]}}if("'"===c||'"'===c||("/"===c||U&&"<"===c&&i.slice(b-1).match(/^<[a-zA-Z:0-9]+\s*([a-zA-Z:0-9]+="[^"]*"\s*)*\/?\s*>/))&&("TK_WORD"===h&&L(a.last_text)||"TK_END_EXPR"===h&&m(t.mode,[I,Q])||m(h,"TK_COMMENT TK_START_EXPR TK_START_BLOCK TK_END_BLOCK TK_OPERATOR TK_EQUALS TK_EOF TK_SEMICOLON TK_COMMA".split(" ")))){var d=c,g=f=!1;l=c;if(b<o)if("/"===d)for(c=!1;f||c||i.charAt(b)!==d;){if(l+=
i.charAt(b),f?f=!1:(f="\\"===i.charAt(b),"["===i.charAt(b)?c=!0:"]"===i.charAt(b)&&(c=!1)),b+=1,b>=o)return[l,"TK_STRING"]}else if(U&&"<"===d){var f=/<(\/?)([a-zA-Z:0-9]+)\s*([a-zA-Z:0-9]+="[^"]*"\s*)*(\/?)\s*>/g,c=i.slice(b-1),e=f.exec(c);if(e&&0===e.index){d=e[2];for(l=0;e;){var g=!!e[1],k=!!e[e.length-1];e[2]===d&&!k&&(g?--l:++l);if(0>=l)break;e=f.exec(c)}d=e?e.index+e[0].length:c.length;b+=d-1;return[c.slice(0,d),"TK_STRING"]}}else for(;f||i.charAt(b)!==d;){l+=i.charAt(b);if(f){if("x"===i.charAt(b)||
"u"===i.charAt(b))g=!0;f=!1}else f="\\"===i.charAt(b);b+=1;if(b>=o)return[l,"TK_STRING"]}b+=1;l+=d;if(g&&Y)a:{c=l;f=!1;e="";l=0;for(var g="",k=0,n;f||l<c.length;)if(n=c.charAt(l),l++,f){f=!1;if("x"===n)g=c.substr(l,2),l+=2;else if("u"===n)g=c.substr(l,4),l+=4;else{e+="\\"+n;continue}if(!g.match(/^[0123456789abcdefABCDEF]+$/)){l=c;break a}k=parseInt(g,16);if(0<=k&&32>k)e="x"===n?e+("\\x"+g):e+("\\u"+g);else if(34===k||39===k||92===k)e+="\\"+String.fromCharCode(k);else if("x"===n&&126<k&&255>=k){l=
c;break a}else e+=String.fromCharCode(k)}else"\\"===n?f=!0:e+=n;l=e}if("/"===d)for(;b<o&&m(i.charAt(b),X);)l+=i.charAt(b),b+=1;return[l,"TK_STRING"]}if("#"===c){if(0===j.length&&"!"===i.charAt(b)){for(l=c;b<o&&"\n"!==c;)c=i.charAt(b),l+=c,b+=1;return[ba(l)+"\n","TK_UNKNOWN"]}d="#";if(b<o&&m(i.charAt(b),ja)){do c=i.charAt(b),d+=c,b+=1;while(b<o&&"#"!==c&&"="!==c);"#"!==c&&("["===i.charAt(b)&&"]"===i.charAt(b+1)?(d+="[]",b+=2):"{"===i.charAt(b)&&"}"===i.charAt(b+1)&&(d+="{}",b+=2));return[d,"TK_WORD"]}}if("<"===
c&&"<\!--"===i.substring(b-1,b+3)){b+=3;for(c="<\!--";"\n"!==i.charAt(b)&&b<o;)c+=i.charAt(b),b++;a.in_html_comment=!0;return[c,"TK_COMMENT"]}if("-"===c&&a.in_html_comment&&"--\>"===i.substring(b-1,b+2))return a.in_html_comment=!1,b+=2,["--\>","TK_COMMENT"];if("."===c)return[c,"TK_DOT"];if(m(c,D)){for(;b<o&&m(c+i.charAt(b),D)&&!(c+=i.charAt(b),b+=1,b>=o););return","===c?[c,"TK_COMMA"]:"="===c?[c,"TK_EQUALS"]:[c,"TK_OPERATOR"]}return[c,"TK_UNKNOWN"]}var i,j,e,E,h,F,x,a,t,W,ea,X,D,b,G,ja,p,T,z,K,d,
o,s,C,ka,J="";ea=["\n","\r","\t"," "];X="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$".split("");ja="0123456789".split("");D="+ - * / % & ++ -- = += -= *= /= %= == === != !== > < >= <= >> << >>> >>>= >>= <<= && &= | || ! !! , : ? ^ ^= |= ::";D+=" <%= <% %> <?= <? ?>";D=D.split(" ");G="continue try throw return var if switch case default for while break function".split(" ");w="Statement";r="ArrayLiteral";Q="ForInitializer";I="Conditional";H="Expression";ka={TK_START_EXPR:function(){da();
if("["===e){if("TK_WORD"===h||")"===a.last_text){m(a.last_text,G)&&(d=!0);A(H);k();N&&(d=!0);return}if(a.mode===r&&("["===a.last_text||","===a.last_text&&("]"===F||"}"===F)))v||f()}else"for"===a.last_text?A(Q):m(a.last_text,["if","while"])?A(I):A(H);if(";"===a.last_text||"TK_START_BLOCK"===h)f();else if("TK_END_EXPR"===h||"TK_START_EXPR"===h||"TK_END_BLOCK"===h||"."===a.last_text)z&&f();else if("TK_WORD"!==h&&"TK_OPERATOR"!==h)d=!0;else if("function"===a.last_word||"typeof"===a.last_word)V&&(d=!0);
else if(m(a.last_text,G)||"catch"===a.last_text)Z&&(d=!0);"("===e&&("TK_EQUALS"===h||"TK_OPERATOR"===h)&&"ObjectLiteral"!==a.mode&&R();k();N&&(d=!0);"["===e&&(A(r),a.indentation_level+=1);T&&(T=!1,a.indentation_level+=1)},TK_END_EXPR:function(){for(;a.mode===w;)B();"]"===e&&(a.mode===r&&a.multiline_array&&!v)&&f();B();N&&(d=!0);k();a.do_while&&t.mode===I&&(t.mode=H,a.do_block=!1,a.do_while=!1)},TK_START_BLOCK:function(){A("BlockStatement");var b=ha("}")&&"function"===a.last_word&&"TK_END_EXPR"===
h;"expand"===n?"TK_OPERATOR"!==h&&(b||"TK_EQUALS"===h||L(a.last_text)&&"else"!==a.last_text)?d=!0:f():"TK_OPERATOR"!==h&&"TK_START_EXPR"!==h?"TK_START_BLOCK"===h?f():d=!0:t.mode===r&&","===a.last_text&&("}"===F?d=!0:f());k();a.indentation_level+=1},TK_END_BLOCK:function(){for(;a.mode===w;)B();B();var b="TK_START_BLOCK"===h;"expand"===n?b||f():b||(a.mode===r&&v?(v=!1,f(),v=!0):f());k()},TK_WORD:function(){da()||z&&(!S(a.mode)&&("TK_OPERATOR"!==h||"--"===a.last_text||"++"===a.last_text)&&"TK_EQUALS"!==
h&&(M||"var"!==a.last_text))&&f();if(a.do_block&&!a.do_while){if("while"===e){d=!0;k();d=!0;a.do_while=!0;return}f();a.do_block=!1}T&&L(e)&&(T=!1);if(a.if_block&&"else"!==e){for(;a.mode===w;)B();a.if_block=!1}if("function"===e){a.var_line&&"TK_EQUALS"!==h&&(a.var_line_reindented=!0);if((y()||";"===a.last_text||"}"===a.last_text)&&"{"!==a.last_text&&a.mode!==r)y()||f(!0),(!y()||!(0<j.length-1&&"\n"===j[j.length-2]))&&f(!0);"TK_WORD"===h?"get"===a.last_text||"set"===a.last_text||"new"===a.last_text||
"return"===a.last_text?d=!0:f():"TK_OPERATOR"===h||"="===a.last_text?d=!0:S(a.mode)||f();k();a.last_word=e}else if("case"===e||"default"===e&&a.in_case_statement){f();if(a.case_body||V)a.indentation_level--,a.case_body=!1;k();a.in_case=!0;a.in_case_statement=!0}else{p="NONE";"TK_END_BLOCK"===h?m(e,["else","catch","finally"])?"expand"===n||"end-expand"===n?p="NEWLINE":(p="SPACE",d=!0):p="NEWLINE":"TK_SEMICOLON"===h&&"BlockStatement"===a.mode?p="NEWLINE":"TK_SEMICOLON"===h&&S(a.mode)?p="SPACE":"TK_STRING"===
h?p="NEWLINE":"TK_WORD"===h?p="SPACE":"TK_START_BLOCK"===h?p="NEWLINE":"TK_END_EXPR"===h&&(d=!0,p="NEWLINE");m(e,G)&&")"!==a.last_text&&(p="else"===a.last_text?"SPACE":"NEWLINE");("TK_COMMA"===h||"TK_START_EXPR"===h||"TK_EQUALS"===h||"TK_OPERATOR"===h)&&"ObjectLiteral"!==a.mode&&R();if(m(e,["else","catch","finally"]))"TK_END_BLOCK"!==h||"expand"===n||"end-expand"===n?f():(ga(!0),"}"!==j[j.length-1]&&f(),d=!0);else if("NEWLINE"===p)if(L(a.last_text))d=!0;else if("TK_END_EXPR"!==h){if(("TK_START_EXPR"!==
h||"var"!==e)&&":"!==a.last_text)"if"===e&&"else"===a.last_word&&"{"!==a.last_text?d=!0:(a.var_line=!1,a.var_line_reindented=!1,f())}else m(e,G)&&")"!==a.last_text&&(a.var_line=!1,a.var_line_reindented=!1,f());else a.mode===r&&","===a.last_text&&"}"===F?f():"SPACE"===p&&(d=!0);k();a.last_word=e;"var"===e&&(a.var_line=!0,a.var_line_reindented=!1,a.var_line_tainted=!1);"do"===e&&(a.do_block=!0);"if"===e&&(a.if_block=!0)}},TK_SEMICOLON:function(){for(;a.mode===w&&!a.if_block;)B();k();a.var_line=!1;a.var_line_reindented=
!1;"ObjectLiteral"===a.mode&&(a.mode="BlockStatement")},TK_STRING:function(){da()?d=!0:"TK_WORD"===h?d=!0:"TK_COMMA"===h||"TK_START_EXPR"===h||"TK_EQUALS"===h||"TK_OPERATOR"===h?"ObjectLiteral"!==a.mode&&R():f();k()},TK_EQUALS:function(){a.var_line&&(a.var_line_tainted=!0);d=!0;k();d=!0},TK_OPERATOR:function(){var b=!0,c=!0;L(a.last_text)?(d=!0,k()):"*"===e&&"TK_DOT"===h&&!F.match(/^\d+$/)?k():":"===e&&a.in_case?(a.case_body=!0,a.indentation_level+=1,k(),f(),a.in_case=!1):"::"===e?k():(z&&("--"===
e||"++"===e)&&f(),m(e,["--","++","!"])||m(e,["-","+"])&&(m(h,["TK_START_BLOCK","TK_START_EXPR","TK_EQUALS","TK_OPERATOR"])||m(a.last_text,G)||","===a.last_text)?(c=b=!1,";"===a.last_text&&S(a.mode)&&(b=!0),"TK_WORD"===h&&m(a.last_text,G)&&(b=!0),("BlockStatement"===a.mode||a.mode===w)&&("{"===a.last_text||";"===a.last_text)&&f()):":"===e?0===a.ternary_depth?("BlockStatement"===a.mode&&(a.mode="ObjectLiteral"),b=!1):a.ternary_depth-=1:"?"===e&&(a.ternary_depth+=1),d=d||b,k(),d=c)},TK_COMMA:function(){if(a.var_line){if(S(a.mode)||
"TK_END_BLOCK"===h)a.var_line_tainted=!1;a.var_line&&(a.var_line_reindented=!0);k();a.var_line_tainted?(a.var_line_tainted=!1,f()):d=!0}else"TK_END_BLOCK"===h&&a.mode!==H?(k(),"ObjectLiteral"===a.mode&&"}"===a.last_text?f():d=!0):"ObjectLiteral"===a.mode?(k(),f()):(k(),d=!0)},TK_BLOCK_COMMENT:function(){for(var a=e,a=a.replace(/\x0d/g,""),b=[],g=a.indexOf("\n");-1!==g;)b.push(a.substring(0,g)),a=a.substring(g+1),g=a.indexOf("\n");a.length&&b.push(a);a:{a=b.slice(1);for(g=0;g<a.length;g++)if("*"!==
ba(a[g]).charAt(0)){a=!1;break a}a=!0}if(a){f(!1,!0);k(b[0]);for(a=1;a<b.length;a++)f(!1,!0),k(" "+ba(b[a]))}else{1<b.length?f(!1,!0):"TK_END_BLOCK"===h?f(!1,!0):d=!0;k(b[0]);j.push("\n");for(a=1;a<b.length;a++)j.push(b[a]),j.push("\n")}ha("\n")||f(!1,!0)},TK_INLINE_COMMENT:function(){d=!0;k();d=!0},TK_COMMENT:function(){z?f(!1,!0):ga(!0);d=!0;k();f(!1,!0)},TK_DOT:function(){L(a.last_text)?d=!0:R(")"===a.last_text&&$);y()&&(T=!0);k()},TK_UNKNOWN:function(){k();"\n"===e[e.length-1]&&f()}};g=g?g:{};
P=aa=O=$=n=Z=V=N=Y=U=v=M=u=void 0;void 0!==g.space_after_anon_function&&void 0===g.jslint_happy&&(g.jslint_happy=g.space_after_anon_function);void 0!==g.braces_on_own_line&&(n=g.braces_on_own_line?"expand":"collapse");n=g.brace_style?g.brace_style:n?n:"collapse";"expand-strict"===n&&(n="expand");O=g.indent_size?parseInt(g.indent_size,10):4;aa=g.indent_char?g.indent_char:" ";M=void 0===g.preserve_newlines?!0:g.preserve_newlines;$=void 0===g.break_chained_methods?!1:g.break_chained_methods;P=void 0===
g.max_preserve_newlines?0:parseInt(g.max_preserve_newlines,10);N=void 0===g.space_in_paren?!1:g.space_in_paren;V=void 0===g.jslint_happy?!1:g.jslint_happy;v=void 0===g.keep_array_indentation?!1:g.keep_array_indentation;Z=void 0===g.space_before_conditional?!0:g.space_before_conditional;Y=void 0===g.unescape_strings?!1:g.unescape_strings;u=void 0===g.wrap_line_length?0:parseInt(g.wrap_line_length,10);U=void 0===g.e4x?!1:g.e4x;for(x="";0<O;)x+=aa,O-=1;for(;q&&(" "===q.charAt(0)||"\t"===q.charAt(0));)J+=
q.charAt(0),q=q.substring(1);i=q;o=q.length;h="TK_START_BLOCK";F="";j=[];d=K=!1;C=[];W=[];A("BlockStatement");b=0;this.beautify=function(){for(var b;;){b=ia();e=b[0];E=b[1];if(E==="TK_EOF")break;if(b=v&&a.mode===r)for(b=0;b<s;b=b+1)f(true);else{z=s>0;P&&s>P&&(s=P);if(M&&s>1){f();for(b=1;b<s;b=b+1)f(true)}}ka[E]();if(E!=="TK_INLINE_COMMENT"&&E!=="TK_COMMENT"&&E!=="TK_UNKNOWN"){F=a.last_text;h=E;a.last_text=e}}return J+j.join("").replace(/[\r\n ]+$/,"")}}"function"===typeof define?define(function(q,
g){g.js_beautify=u}):"undefined"!==typeof exports?exports.js_beautify=u:"undefined"!==typeof window?window.js_beautify=u:"undefined"!==typeof global&&(global.js_beautify=u)})();