definitions:
  config:
    /hippo:configuration/hippo:translations/hippo:workflows:
      jcr:primaryType: hipposys:resourcebundles
      /en:
        jcr:primaryType: hipposys:resourcebundle
        admin: Administration
        committype: Type actions
