definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-tree-views:
      jcr:primaryType: frontend:clusterfolder
      /documents:
        jcr:primaryType: frontend:plugincluster
        frontend:properties: [use.width.from.classname, bind.to.layout.unit, workflow.enabled,
          nodetypes, root.path]
        frontend:references: [browser.id, editor.id]
        frontend:services: [wicket.id, model.folder]
        model.folder: ${cluster.id}.model.folder
        nodetypes: []
        root.path: /content/documents
        /sectionPlugin:
          jcr:primaryType: frontend:plugin
          extension.addfolder: ${cluster.id}.addfolder
          extension.tree: ${cluster.id}.tree
          model.folder.root: ${root.path}
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.section.SearchingSectionPlugin
          title: section-documents
          wicket.extensions: [extension.tree, extension.addfolder]
        /documentsBrowser:
          jcr:primaryType: frontend:plugin
          path: ${root.path}
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.tree.FolderTreePlugin
          rootless: 'true'
          wicket.id: ${cluster.id}.tree
          wicket.model: ${model.folder}
          /module.workflow:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.addon.workflow.ContextWorkflowManagerPlugin
            workflow.categories: [threepane, folder-translations]
          /filters:
            jcr:primaryType: frontend:pluginconfig
            /showFolderType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:folder
              display: true
            /showDirectoryType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:directory
              display: true
            /hideHandleType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:handle
              display: false
            /hideResultsetType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:facetresult
              display: false
            /hideFacNavType:
              jcr:primaryType: frontend:pluginconfig
              child: hippofacnav:facetnavigation
              display: false
        /addfolderPlugin:
          jcr:primaryType: frontend:plugin
          option.location: /content/documents
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.FolderShortcutPlugin
          wicket.id: ${cluster.id}.addfolder
          wicket.variant: addfolder
          workflow.categories: threepane
          workflow.translated: new-translated-folder
      /images:
        jcr:primaryType: frontend:plugincluster
        frontend:properties: [use.width.from.classname, bind.to.layout.unit, workflow.enabled,
          nodetypes]
        frontend:references: [browser.id, editor.id]
        frontend:services: [wicket.id, model.folder]
        model.folder: ${cluster.id}.model.folder
        /sectionPlugin:
          jcr:primaryType: frontend:plugin
          extension.addfolder: ${cluster.id}.addfolder
          extension.tree: ${cluster.id}.tree
          model.folder.root: /content/gallery
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.section.SearchingSectionPlugin
          title: section-images
          wicket.extensions: [extension.tree, extension.addfolder]
        /imagesBrowser:
          jcr:primaryType: frontend:plugin
          nodename.max.length: 23
          path: /content/gallery
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.tree.FolderTreePlugin
          rootless: 'true'
          wicket.id: ${cluster.id}.tree
          wicket.model: ${model.folder}
          /module.workflow:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.addon.workflow.ContextWorkflowManagerPlugin
            workflow.categories: [gallery, threepane]
          /filters:
            jcr:primaryType: frontend:pluginconfig
            /showGalleryType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:gallery
              display: true
            /hideUnstructuredType:
              jcr:primaryType: frontend:pluginconfig
              child: nt:unstructured
              display: false
            /hideHandleType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:handle
              display: false
            /hideFacetSearchType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:facetsearch
              display: false
            /hideFolderType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:folder
              display: false
            /hideDirectoryType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:directory
              display: false
            /hideFacNavType:
              jcr:primaryType: frontend:pluginconfig
              child: hippofacnav:facetnavigation
              display: false
        /addfolderPlugin:
          jcr:primaryType: frontend:plugin
          option.location: /content/gallery
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.FolderShortcutPlugin
          wicket.id: ${cluster.id}.addfolder
          wicket.variant: addfolder
          workflow.categories: threepane
      /assets:
        jcr:primaryType: frontend:plugincluster
        frontend:properties: [use.width.from.classname, bind.to.layout.unit, workflow.enabled,
          nodetypes]
        frontend:references: [browser.id, editor.id]
        frontend:services: [wicket.id, model.folder]
        model.folder: ${cluster.id}.model.folder
        /sectionPlugin:
          jcr:primaryType: frontend:plugin
          extension.addfolder: ${cluster.id}.addfolder
          extension.tree: ${cluster.id}.tree
          model.folder.root: /content/assets
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.section.SearchingSectionPlugin
          title: section-files
          wicket.extensions: [extension.tree, extension.addfolder]
        /filesBrowser:
          jcr:primaryType: frontend:plugin
          nodename.max.length: 23
          path: /content/assets
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.tree.FolderTreePlugin
          rootless: 'true'
          wicket.id: ${cluster.id}.tree
          wicket.model: ${model.folder}
          /module.workflow:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.addon.workflow.ContextWorkflowManagerPlugin
            workflow.categories: [gallery, threepane]
          /filters:
            jcr:primaryType: frontend:pluginconfig
            /showGalleryType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:gallery
              display: true
            /hideUnstructuredType:
              jcr:primaryType: frontend:pluginconfig
              child: nt:unstructured
              display: false
            /hideHandleType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:handle
              display: false
            /hideFacetSearchType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:facetsearch
              display: false
            /hideFolderType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:folder
              display: false
            /hideDirectoryType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:directory
              display: false
            /hideFacNavType:
              jcr:primaryType: frontend:pluginconfig
              child: hippofacnav:facetnavigation
              display: false
        /addfolderPlugin:
          jcr:primaryType: frontend:plugin
          option.location: /content/assets
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.FolderShortcutPlugin
          wicket.id: ${cluster.id}.addfolder
          wicket.variant: addfolder
          workflow.categories: threepane
      /configuration:
        jcr:primaryType: frontend:plugincluster
        frontend:properties: [use.width.from.classname, bind.to.layout.unit, workflow.enabled]
        frontend:references: [browser.id, editor.id]
        frontend:services: [wicket.id, model.folder]
        model.folder: ${cluster.id}.model.folder
        /sectionPlugin:
          jcr:primaryType: frontend:plugin
          extension.tree: ${cluster.id}.tree
          model.folder.root: /hippo:namespaces
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.section.BrowsingSectionPlugin
          title: section-configuration
          wicket.extensions: extension.tree
        /configurationBrowser:
          jcr:primaryType: frontend:plugin
          nodename.max.length: 23
          path: /hippo:namespaces
          plugin.class: org.hippoecm.frontend.plugins.cms.browse.tree.FolderTreePlugin
          rootless: 'false'
          wicket.id: ${cluster.id}.tree
          wicket.model: ${model.folder}
          /module.workflow:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.addon.workflow.ContextWorkflowManagerPlugin
            workflow.categories: editor
          /filters:
            jcr:primaryType: frontend:pluginconfig
            /showNamespacesAsDocumentTypes:
              jcr:primaryType: frontend:pluginconfig
              display: true
              name: document types
              path: /hippo:namespaces
            /hideChildrenOfNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              parent: hipposysedit:namespace
            /hideHippoNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/hippo
            /hideGalleryNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/hippogallery
            /hideHippostdNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/hippostd
            /hideHippostdpubwfNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/hippostdpubwf
            /hideSystemNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/system
            /hideFrontendNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/frontend
            /hideHipposyseditNamespace:
              jcr:primaryType: frontend:pluginconfig
              display: false
              path: /hippo:namespaces/hipposysedit
            /showOtherNamespaces:
              jcr:primaryType: frontend:pluginconfig
              child: hipposysedit:namespace
              display: true
            /hideFolderType:
              jcr:primaryType: frontend:pluginconfig
              child: hippostd:folder
              display: false
            /hideHandleType:
              jcr:primaryType: frontend:pluginconfig
              child: hippo:handle
              display: false
