definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-services/logoutService:
      jcr:primaryType: frontend:plugin
      plugin.class: org.hippoecm.frontend.logout.CmsLogoutService
