definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-services/passwordValidationService:
      jcr:primaryType: frontend:plugin
      password.strength: 3
      plugin.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.PasswordValidationServiceImpl
      /minimalLengthValidator:
        jcr:primaryType: frontend:pluginconfig
        minimallength: 8
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.MinimalLengthPasswordValidator
      /containsCapitalValidator:
        jcr:primaryType: frontend:pluginconfig
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.ContainsCapitalPasswordValidator
      /isNoPreviousValidator:
        jcr:primaryType: frontend:pluginconfig
        numberofpreviouspasswords: 5
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.IsNoPreviousPasswordValidator
      /containsNoNameValidator:
        jcr:primaryType: frontend:pluginconfig
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.ContainsNoNamePasswordValidator
      /containsLowercaseValidator:
        jcr:primaryType: frontend:pluginconfig
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.ContainsLowercasePasswordValidator
      /containsSpecialCharacterValidator:
        jcr:primaryType: frontend:pluginconfig
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.ContainsSpecialCharacterPasswordValidator
      /containsDigitValidator:
        jcr:primaryType: frontend:pluginconfig
        validator.class: org.hippoecm.frontend.plugins.cms.admin.password.validation.ContainsDigitPasswordValidator
