definitions:
  config:
    /hippo:configuration/hippo:translations/hippo:cms/sections:
      jcr:primaryType: hipposys:resourcebundles
      /en:
        jcr:primaryType: hipposys:resourcebundle
        section-configuration: Document Types
        section-documents: Documents
        section-files: Assets
        section-images: Images
