package org.onehippo.cms7.essentials.dashboard.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.ANNOTATION_TYPE;
import static java.lang.annotation.ElementType.CONSTRUCTOR;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.LOCAL_VARIABLE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PACKAGE;
import static java.lang.annotation.ElementType.PARAMETER;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.SOURCE;

/**
 * Used to mark source code that has been generated by HippoEssentials
 *
 * @version "$Id: HippoEssentialsGenerated.java 173277 2013-08-09 10:06:29Z mmilicevic $"
 */

@Documented
@Retention(SOURCE)
@Target({PACKAGE, TYPE, ANNOTATION_TYPE, METHOD, CONSTRUCTOR, FIELD,
        LOCAL_VARIABLE, PARAMETER})
public @interface HippoEssentialsGenerated {

    /**
     * Name used by hippo essentials code generator.
     * User can safely rename generated  property (e.g. class name, method name),
     * HippoEssentials framework will check internal name before generating mentioned property
     *
     * @return internal name of generated code
     */
    String internalName() default "";

    /**
     * Indicates if generated code may be modified by HippoEssentials code generators
     *
     * @return true by default
     */
    boolean allowModifications() default true;

}
