//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 01:46:58 PM CEST 
//

@XmlSchema(namespace = "http://www.google.com/schemas/sitemap-news/0.9", elementFormDefault = XmlNsForm.QUALIFIED)
package org.onehippo.forge.sitemap.components.model.news.info;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;