definitions:
  config:
    /hippo:configuration:
      jcr:primaryType: hipposys:configuration
      /hippo:derivatives:
        jcr:primaryType: hipposys:derivativesfolder
        /hippo:corederivatives:
          jcr:primaryType: hipposys:deriveddefinition
          hipposys:classname: org.hippoecm.repository.deriveddata.CoreDerivedDataFunction
          hipposys:nodetype: hippo:document
          hipposys:serialver: 1
          /hipposys:accessed:
            jcr:primaryType: hipposys:propertyreferences
            /ancestors:
              jcr:primaryType: hipposys:builtinpropertyreference
              hipposys:method: ancestors
          /hipposys:derived:
            jcr:primaryType: hipposys:propertyreferences
            /ancestors:
              jcr:primaryType: hipposys:relativepropertyreference
              hipposys:relPath: hippo:paths
      /hippo:temporary:
        .meta:category: system
      /hippo:queries:
        jcr:primaryType: hipposys:queryfolder
      /hippo:workflows:
        jcr:primaryType: hipposys:workflowfolder
        jcr:uuid: c89f56e5-5e9d-4967-9850-7b6254d1791c
      /hippo:domains:
        jcr:primaryType: hipposys:domainfolder
      /hippo:security:
        jcr:primaryType: hipposys:securityfolder
        /internal:
          jcr:primaryType: hipposys:securityprovider
          hipposys:classname: org.hippoecm.repository.security.RepositorySecurityProvider
          /hipposys:userprovider:
            jcr:primaryType: hipposys:userprovider
            hipposys:dirlevels: 0
          /hipposys:groupprovider:
            jcr:primaryType: hipposys:groupprovider
            hipposys:dirlevels: 0
        /hipposys:accessmanager:
          jcr:primaryType: hipposys:accessmanager
          hipposys:permissioncachesize: 20000
      /hippo:users:
        jcr:primaryType: hipposys:userfolder
        .meta:residual-child-node-category: system
      /hippo:groups:
        jcr:primaryType: hipposys:groupfolder
        .meta:residual-child-node-category: system
      /hippo:roles:
        jcr:primaryType: hipposys:rolefolder
        .meta:residual-child-node-category: system
      /hippo:userroles:
        jcr:primaryType: hipposys:userrolefolder
        .meta:residual-child-node-category: system
      /hippo:frontend:
        jcr:primaryType: hipposys:applicationfolder
      /hippo:modules:
        jcr:primaryType: hipposys:modulefolder
        jcr:lockOwner:
          .meta:category: system
        jcr:lockIsDeep:
          .meta:category: system
