definitions:
  config:
    /hippo:configuration/hippo:domains/hippolog:
      jcr:primaryType: hipposys:domain
      /hippolog-item:
        jcr:primaryType: hipposys:domainrule
        /type-hippolog-item:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hippolog:item
      /hippolog-folder:
        jcr:primaryType: hipposys:domainrule
        /type-hippolog-folder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hippolog:folder
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [everybody]
        hipposys:role: readonly
