definitions:
  config:
    /hippo:configuration/hippo:domains/defaultread/hippo-compound:
      jcr:primaryType: hipposys:domainrule
      /type-hippo-compound:
        jcr:primaryType: hipposys:facetrule
        hipposys:equals: true
        hipposys:facet: nodetype
        hipposys:filter: false
        hipposys:type: Name
        hipposys:value: hippo:compound
