definitions:
  config:
    /hippo:configuration/hippo:domains/hippodocuments:
      jcr:primaryType: hipposys:domain
      /hippo-document:
        jcr:primaryType: hipposys:domainrule
        /nodetype-hippo-document:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hippo:document
        /hide-prototypes:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: false
          hipposys:facet: nodename
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hipposysedit:prototype
      /editor:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [admin, editor]
        hipposys:role: editor
      /author:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [author]
        hipposys:role: author
