definitions:
  config:
    /hippo:configuration/hippo:domains/hipporequests:
      jcr:primaryType: hipposys:domain
      /hippo-request:
        jcr:primaryType: hipposys:domainrule
        /nodetype-hippo-request:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hippo:request
      /editor:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor]
        hipposys:role: editor
      /author:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [author]
        hipposys:role: author
