definitions:
  config:
    /hippo:configuration/hippo:update:
      jcr:primaryType: hipposys:update
      jcr:lockOwner:
        .meta:category: system
      jcr:lockIsDeep:
        .meta:category: system
      /hippo:registry:
        .meta:residual-child-node-category: content
        jcr:primaryType: hipposys:updaterfolder
      /hippo:queue:
        .meta:residual-child-node-category: content
        jcr:primaryType: hipposys:updaterfolder
      /hippo:history:
        .meta:residual-child-node-category: system
        jcr:primaryType: hipposys:updaterfolder
