/*
 * Copyright 2019-2020 BloomReach. All rights reserved. (https://www.bloomreach.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface EventCoordinates {
  x: number;
  y: number;
  wheel: boolean;
}

/**
 * Normalize the amount of pixels to scroll from a wheel event as Firefox and Chrome have different implementations.
 * A single 'tick' of the scroll-wheel amounts for approximately 40 pixels.
 *
 * This coded is a simplified version of:
 * https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js
 */
export function normalizeWheelEvent(event: any): EventCoordinates {
  if (event.deltaMode === 1) { // Firefox with mouse scroll-wheel
    return {
      x: event.deltaX * 40,
      y: event.deltaY * 40,
      wheel: true,
    };
  }

  return {
    x: event.deltaX,
    y: event.deltaY,
    // Chrome exposes wheelDeltaY with increments of 120/-120 when wheel events are generated by a scroll wheel
    wheel: !!(event.wheelDeltaY && (event.wheelDeltaY >= 120 || event.wheelDeltaY <= -120)),
  };
}
