package org.hippoecm.hst.core.container;

import java.io.IOException;
import java.util.Map;

import org.hippoecm.hst.core.component.HstComponent;

/**
 * HST Component Window.
 * This interface represents a fragment window of a page which is generated by a HstComponent.
 * 
 * @version $Id$
 */
public interface HstComponentWindow {

    /**
     * The reference name of the component window.
     * 
     * @return the reference name of the component window
     */
    String getReferenceName();
    
    /**
     * The reference namespace of the component window.
     * 
     * @return the reference namespace of the component window
     */
    String getReferenceNamespace();

    /**
     * The actual HstComponent instance.
     * 
     * @return the actual HstComponent instance
     */
    HstComponent getComponent();
    
    /**
     * The dispatching path path to render this component window.
     * 
     * @return the dispatching path to render this component window
     */
    String getRenderPath(); 
    
    /**
     * The parent component window containing this component window.
     * 
     * @return the component window containing this component window
     */
    HstComponentWindow getParentWindow();
    
    /**
     * The child component windows contained in this component window.
     * 
     * @return the component windows contained in this component window
     */
    Map<String, HstComponentWindow> getChildWindowMap();
    
    /**
     * The child component window which can be accessed by the path.
     * 
     * @param referenceName the referenceName of the child component window
     * @return the child component window which has the referenceName
     */
    HstComponentWindow getChildWindow(String referenceName);
    
    /**
     * Flushes the output content of this component window
     * 
     * @throws IOException
     */
    void flushContent() throws IOException;
    
}
